FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

COPY packages-Edgeric.txt /tmp/packages-Edgeric.txt

RUN apt-get update && apt-get -y upgrade && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:gnuradio/gnuradio-releases && \
    apt-get update && \
    awk '/^\[apt\]/{flag=1;next}/^\[/{flag=0}flag' /tmp/packages-Edgeric.txt | \
      xargs -r apt-get install -y && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip && \
    pip3 uninstall -y protobuf || true && \
    awk '/^\[pip\]/{flag=1;next}/^\[/{flag=0}flag' /tmp/packages-Edgeric.txt | \
      xargs -r pip3 install

RUN mkdir -p /home/EdgeRIC
WORKDIR "/home/EdgeRIC"
COPY . .

COPY setup_netns.sh /opt/EdgeRIC/setup_netns.sh
RUN chmod +x /opt/EdgeRIC/setup_netns.sh

WORKDIR /home/EdgeRIC
CMD [ "/opt/EdgeRIC/setup_netns.sh" ]
